//
// Created by wndws on 5/26/2024.
//

#ifndef PROIECT_COLECTIV_CUSTOMERCONTROLLER_H
#define PROIECT_COLECTIV_CUSTOMERCONTROLLER_H


class CustomerController {

};


#endif //PROIECT_COLECTIV_CUSTOMERCONTROLLER_H
