//
// Created by wndws on 5/26/2024.
//

#ifndef PROIECT_COLECTIV_EMPLOYEECONTROLLER_H
#define PROIECT_COLECTIV_EMPLOYEECONTROLLER_H


class EmployeeController {

};


#endif //PROIECT_COLECTIV_EMPLOYEECONTROLLER_H
